### PR TITLE
pass bounding box to selection callback

### PR DESCRIPTION
**Pull request by joshua-gould**

### CODE REVIEW

**Comment by cannoneyed** [comment]
Hey @joshua-gould, thanks for sending this over - unfortunately I literally updated the `onSelect` method on Friday, so there's gonna be a few conflicts here - mind straightening them out? Just FYI I added a separate `select` method so that the semantics were a bit clearer (`select` is to explicitly make things selected, and `onSelect` is a callback interface for listening to user selection events)

**Comment by cannoneyed** [comment]
I think this is going to be a very useful PR as well - mind rebasing onto master so I can get a clean diff? Lots of stuff changed with the `onSelect` method in the time you were working on this!

**Comment by cannoneyed** [comment]
Mind cleaning this one up if you still want it?

**Comment by joshua-gould** [comment]
I think we can close this request and rethink the callback with https://github.com/PAIR-code/scatter-gl/issues/39#issuecomment-614123975.

**Pull request closed without merging**
